### PR TITLE
Local message classes and improved robustness

### PR DESCRIPTION
**Pull request by Zeverin**
Improved the structure of the code and improved the robustness. These changes should make the stack much more resilient against incorrect input data. Specifically the stack will check every value coming from Simulink to verify that they are within the range of values for that element, and if not it will replace the incorrect value with "unknown" if that can be done in a safe way. By safe way I mean that it is safer to send a message with an "unknown" than dropping the message. Otherwise it will drop the message. Previously it would always drop incorrect messages without attempting to fix them.

### CODE REVIEW

**Comment by alexvoronov** [comment]
There's an error in the travis build:

SLF4J: Class path contains multiple SLF4J bindings.

Do you know what's wrong?

**Comment by Zeverin** [comment]
It compiles fine locally but maybe there's a problem with several conflicting logback.xml files?

**Comment by alexvoronov** [comment]
Do you have access to the Travis CI error messages? Here is a direct link to the log: https://api.travis-ci.org/jobs/105517296/log.txt?deansi=true

I think it might be related to the conflicting logback files, but I haven't tried compiling and testing yet.

**Comment by Zeverin** [comment]
It seems to fail on the commit where I deleted the "LocalCAM" file. I renamed that file to "LocalCam" locally but when I pushed to git both "LocalCAM" and "LocalCam" existed in the repo so I deleted the "LocalCAM" file in the web gui. Seems like this is the source of the problem. Not sure how to fix that but I'll have another look tomorrow.

**Comment by Zeverin** [comment]
I've renamed the logback.xml file in the vehicle-adapter folder and this seems to have resolved the problem.

**Pull request merged**
